"""User-editable settings with safe default merging and persistence."""

from __future__ import annotations

import json
import math
import os
import tempfile
import tomllib
from collections.abc import Mapping
from copy import deepcopy
from pathlib import Path
from typing import Any

from app.infrastructure.config import ConfigManager, DEFAULT_CONFIG_PATH
from app.infrastructure.paths import user_config_path

DEFAULT_USER_CONFIG_PATH = user_config_path()

# Only values represented by the settings page and existing non-secret
# compatibility options may be written. Secret credentials are deliberately
# excluded and are stored by app.ai.secrets in Windows Credential Manager.
ALLOWED_USER_KEYS: dict[str, set[str]] = {
    "translation": {
        "source_language",
        "target_language",
    },
    "ai": {
        "provider",
        "model",
        "base_url",
        "chat_selection_capture_enabled",
    },
    "trigger": {"mode", "hotkey", "debounce_ms"},
    "overlay": {
        "position_mode",
        "font_family",
        "font_size",
        "opacity",
        "background_opacity",
        "text_opacity",
        "max_width",
        "locked",
        "theme",
        "show_original",
        "margin",
        "custom_position_x",
        "custom_position_y",
        "mouse_offset_x",
        "mouse_offset_y",
    },
    "cache": {
        "enabled",
        "max_size",
        "sqlite_enabled",
        "sqlite_path",
        "history_enabled",
    },
    "google_web": {
        "enabled",
        "endpoint",
        "timeout_ms",
        "max_retries",
        "min_interval_ms",
    },
    # Preserve safe legacy keys when an older installation is saved by the
    # new settings layer. No credential or token sections are accepted.
    "input": {
        "hotkey",
        "hotkey_debounce_ms",
        "auto_selection_enabled",
        "auto_selection_debounce_ms",
    },
    "selection": {"uia_timeout_ms"},
}


def _deep_merge(
    base: Mapping[str, Any],
    override: Mapping[str, Any],
) -> dict[str, Any]:
    """Recursively merge mapping values without mutating either input."""

    result: dict[str, Any] = deepcopy(dict(base))
    for key, value in override.items():
        if (
            isinstance(result.get(key), Mapping)
            and isinstance(value, Mapping)
        ):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = deepcopy(value)
    return result


def _load_toml(path: Path) -> dict[str, Any]:
    try:
        with path.open("rb") as config_file:
            loaded = tomllib.load(config_file)
    except (OSError, tomllib.TOMLDecodeError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def _safe_user_data(data: Mapping[str, Any]) -> dict[str, Any]:
    """Keep only scalar, known, non-sensitive user configuration values."""

    safe: dict[str, Any] = {}
    for section, allowed_keys in ALLOWED_USER_KEYS.items():
        values = data.get(section)
        if not isinstance(values, Mapping):
            continue
        safe_values: dict[str, Any] = {}
        for key in allowed_keys:
            value = values.get(key)
            if isinstance(value, (str, bool, int, float)):
                if isinstance(value, float) and not math.isfinite(value):
                    continue
                safe_values[key] = deepcopy(value)
        if safe_values:
            safe[section] = safe_values
    return safe


def _toml_literal(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float) and math.isfinite(value):
        return repr(value)
    raise ValueError("unsupported TOML value")


def _dump_toml(data: Mapping[str, Any]) -> str:
    """Serialize the known one-level settings structure without extra deps."""

    lines: list[str] = [
        "# Generated by Desktop Translator. Do not store secrets here.",
        "",
    ]
    for section, values in data.items():
        if not isinstance(values, Mapping):
            continue
        scalar_values = [
            (key, value)
            for key, value in values.items()
            if not isinstance(value, Mapping)
        ]
        if not scalar_values:
            continue
        lines.append(f"[{section}]")
        for key, value in scalar_values:
            lines.append(f"{key} = {_toml_literal(value)}")
        lines.append("")
    return "\n".join(lines)


class SettingsManager(ConfigManager):
    """Merge read-only defaults with a safe, user-owned TOML file.

    ``config/default.toml`` remains the shipped baseline. Only
    ``config/user.toml`` is written, and only whitelisted settings are
    persisted there. Missing or malformed user settings simply fall back to
    the defaults and never prevent application startup.
    """

    def __init__(
        self,
        default_path: str | Path | None = None,
        user_path: str | Path | None = None,
        *,
        default_config_path: str | Path | None = None,
        user_config_path: str | Path | None = None,
    ) -> None:
        if default_config_path is not None:
            default_path = default_config_path
        if user_config_path is not None:
            user_path = user_config_path
        self.default_path = (
            Path(default_path) if default_path is not None else DEFAULT_CONFIG_PATH
        )
        self.user_path = (
            Path(user_path) if user_path is not None else DEFAULT_USER_CONFIG_PATH
        )
        # ``path`` is retained for compatibility with ConfigManager callers.
        self.path = self.default_path
        self._data: dict[str, Any] = {}
        self._user_data: dict[str, Any] = {}
        self.reload()

    @property
    def user_data(self) -> dict[str, Any]:
        """Return a defensive copy of the persisted, non-secret settings."""

        return deepcopy(self._user_data)

    @property
    def data(self) -> dict[str, Any]:
        """Return a defensive copy of the merged effective settings."""

        return deepcopy(self._data)

    def reload(self) -> dict[str, Any]:
        """Reload defaults and user settings from disk."""

        defaults = _load_toml(self.default_path)
        self._user_data = _safe_user_data(_load_toml(self.user_path))
        self._data = _deep_merge(defaults, self._user_data)
        self._apply_legacy_overlay_opacity()
        return self.data

    def _apply_legacy_overlay_opacity(self) -> None:
        """Make an old user opacity value the effective background value."""

        user_overlay = self._user_data.get("overlay", {})
        effective_overlay = self._data.get("overlay")
        if (
            isinstance(user_overlay, Mapping)
            and "background_opacity" not in user_overlay
            and "opacity" in user_overlay
            and isinstance(effective_overlay, dict)
        ):
            effective_overlay["background_opacity"] = user_overlay["opacity"]

    load = reload

    def save(self, values: Mapping[str, Any] | None = None) -> dict[str, Any]:
        """Persist a sanitized update and return the merged effective config."""

        update = _safe_user_data(values or {})
        self._user_data = _safe_user_data(_deep_merge(self._user_data, update))
        self.user_path.parent.mkdir(parents=True, exist_ok=True)

        temporary_path: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                newline="\n",
                prefix=f".{self.user_path.stem}-",
                suffix=".tmp",
                dir=self.user_path.parent,
                delete=False,
            ) as temporary_file:
                temporary_path = Path(temporary_file.name)
                temporary_file.write(_dump_toml(self._user_data))
                temporary_file.flush()
                os.fsync(temporary_file.fileno())
            os.replace(temporary_path, self.user_path)
        except Exception:
            if temporary_path is not None:
                try:
                    temporary_path.unlink(missing_ok=True)
                except OSError:
                    pass
            raise

        self._data = _deep_merge(_load_toml(self.default_path), self._user_data)
        self._apply_legacy_overlay_opacity()
        return self.data

    save_settings = save
    save_config = save
    update = save

    def set(self, section: str, key: str, value: Any) -> dict[str, Any]:
        """Persist one known setting using the same whitelist as ``save``."""

        return self.save({section: {key: value}})

    load_config = reload


__all__ = [
    "ALLOWED_USER_KEYS",
    "DEFAULT_USER_CONFIG_PATH",
    "SettingsManager",
]
