"""RAG domain contracts and ingestion boundary for AITrans knowledge retrieval."""

from backend.rag.chunking import CHUNKER_VERSION, StructureAwareChunker, chunk_document
from backend.rag.citation_service import CitationService, build_evidence_citations
from backend.rag.config import (
    RagAdvancedParsingConfig,
    RagChunkingConfig,
    RagConfig,
    RagEmbeddingConfig,
    RagRerankerConfig,
    RagRetrievalConfig,
    RagSemanticChunkingConfig,
    RagVectorStoreConfig,
)
from backend.rag.context_builder import GroundedContext, GroundedContextBuilder
from backend.rag.document_tree import (
    DocumentParagraphNode,
    DocumentSectionNode,
    DocumentTree,
    DocumentTreeBuilder,
)
from backend.rag.embeddings import (
    EmbeddingProvider,
    EmbeddingRuntimeSnapshot,
    EmbeddingRuntimeStatus,
    Qwen3EmbeddingProvider,
    create_embedding_provider,
)
from backend.rag.evaluation import RagEvaluationReport, evaluate_rag
from backend.rag.evaluation_dataset import (
    RagClaimPrediction,
    RagEvaluationCase,
    RagEvaluationClaim,
    RagEvaluationLatency,
    RagEvaluationPrediction,
    load_evaluation_dataset,
    load_evaluation_predictions,
)
from backend.rag.evidence_builder import build_agent_evidence, build_evidence_item
from backend.rag.exceptions import (
    RagConfigurationError,
    RagEmbeddingError,
    RagError,
    RagInvariantError,
    RagModelManagerError,
    RagParsingError,
    RagRetrievalError,
    RagVectorStoreError,
    UnsupportedDocumentTypeError,
)
from backend.rag.index_manifest import IndexManifest, IndexManifestRecord, IndexStatus
from backend.rag.index_service import IndexDocumentResult, IndexService
from backend.rag.model_manager import (
    EMBEDDING_MODEL_ID,
    RERANKER_MODEL_ID,
    ModelManager,
    default_models_root,
)
from backend.rag.models import (
    DocumentChunk,
    DocumentElement,
    DocumentModality,
    DocumentPage,
    DocumentSection,
    KnowledgeDocument,
    NormalizedDocument,
    RetrievalCandidate,
    RetrievalContextWindow,
    RetrievalResult,
    build_stable_chunk_id,
)
from backend.rag.multimodal import (
    MULTIMODAL_INDEX_VERSION,
    augment_document_with_visual_elements,
    build_multimodal_chunks,
    extract_visual_elements,
)
from backend.rag.parsers import (
    AdvancedParserWithFallback,
    DoclingDocumentParser,
    get_parser_for_path,
    parse_document,
)
from backend.rag.performance import (
    BASELINE_VARIANT,
    RagEmbeddingBenchmark,
    RagPerformanceCandidate,
    RagPerformanceComparison,
    RagPerformanceVariant,
    benchmark_embedding_batches,
    compare_performance_candidates,
    config_for_variant,
    performance_sweeps,
)
from backend.rag.query_planner import RagQueryPlan, RagQueryPlanner, merge_query_results
from backend.rag.semantic_chunking import (
    SEMANTIC_CHUNKER_VERSION,
    SemanticStructureAwareChunker,
)
from backend.rag.small_to_big import SmallToBigContextExpander
from backend.rag.tokenization import (
    HeuristicTokenCounter,
    TokenCounter,
    TransformersTokenCounter,
)

__all__ = [
    "BASELINE_VARIANT",
    "CHUNKER_VERSION",
    "EMBEDDING_MODEL_ID",
    "MULTIMODAL_INDEX_VERSION",
    "RERANKER_MODEL_ID",
    "SEMANTIC_CHUNKER_VERSION",
    "AdvancedParserWithFallback",
    "CitationService",
    "DoclingDocumentParser",
    "DocumentChunk",
    "DocumentElement",
    "DocumentModality",
    "DocumentPage",
    "DocumentParagraphNode",
    "DocumentSection",
    "DocumentSectionNode",
    "DocumentTree",
    "DocumentTreeBuilder",
    "EmbeddingProvider",
    "EmbeddingRuntimeSnapshot",
    "EmbeddingRuntimeStatus",
    "GroundedContext",
    "GroundedContextBuilder",
    "HeuristicTokenCounter",
    "IndexDocumentResult",
    "IndexManifest",
    "IndexManifestRecord",
    "IndexService",
    "IndexStatus",
    "KnowledgeDocument",
    "ModelManager",
    "NormalizedDocument",
    "Qwen3EmbeddingProvider",
    "RagAdvancedParsingConfig",
    "RagChunkingConfig",
    "RagClaimPrediction",
    "RagConfig",
    "RagConfigurationError",
    "RagEmbeddingBenchmark",
    "RagEmbeddingConfig",
    "RagEmbeddingError",
    "RagError",
    "RagEvaluationCase",
    "RagEvaluationClaim",
    "RagEvaluationLatency",
    "RagEvaluationPrediction",
    "RagEvaluationReport",
    "RagInvariantError",
    "RagModelManagerError",
    "RagParsingError",
    "RagPerformanceCandidate",
    "RagPerformanceComparison",
    "RagPerformanceVariant",
    "RagQueryPlan",
    "RagQueryPlanner",
    "RagRerankerConfig",
    "RagRetrievalConfig",
    "RagRetrievalError",
    "RagSemanticChunkingConfig",
    "RagVectorStoreConfig",
    "RagVectorStoreError",
    "RetrievalCandidate",
    "RetrievalContextWindow",
    "RetrievalResult",
    "SemanticStructureAwareChunker",
    "SmallToBigContextExpander",
    "StructureAwareChunker",
    "TokenCounter",
    "TransformersTokenCounter",
    "UnsupportedDocumentTypeError",
    "augment_document_with_visual_elements",
    "benchmark_embedding_batches",
    "build_agent_evidence",
    "build_evidence_citations",
    "build_evidence_item",
    "build_multimodal_chunks",
    "build_stable_chunk_id",
    "chunk_document",
    "compare_performance_candidates",
    "config_for_variant",
    "create_embedding_provider",
    "default_models_root",
    "evaluate_rag",
    "extract_visual_elements",
    "get_parser_for_path",
    "load_evaluation_dataset",
    "load_evaluation_predictions",
    "merge_query_results",
    "parse_document",
    "performance_sweeps",
]
